# Generated by Django 2.2.7 on 2020-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('shrinked_url', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('complete_url', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visited_count', models.IntegerField(default=0)),
            ],
        ),
    ]
